export const coinsType = [
  { value: 'USD', label: 'Dólar Americano' },
  { value: 'EUR', label: 'Euro' },
  { value: 'BRL', label: 'Real Brasileiro' },
  { value: 'GBP', label: 'Libra Esterlina' },
  { value: 'JPY', label: 'Iene Japonês' },
  { value: 'CNY', label: 'Yuan Chinês' },
  { value: 'CAD', label: 'Dólar Canadense' },
  { value: 'AUD', label: 'Dólar Australiano' },
  { value: 'CHF', label: 'Franco Suíço' },
  { value: 'BTC', label: 'Bitcoin' },
  { value: 'ETH', label: 'Ethereum' },
  { value: 'AED', label: 'Dirham dos Emirados' },
  { value: 'AFN', label: 'Afghani do Afeganistão' },
  { value: 'ALL', label: 'Lek Albanês' },
  { value: 'AMD', label: 'Dram Armênio' },
  { value: 'ANG', label: 'Guilder das Antilhas' },
  { value: 'AOA', label: 'Kwanza Angolano' },
  { value: 'ARS', label: 'Peso Argentino' },
  { value: 'AZN', label: 'Manat Azeri' },
  { value: 'BAM', label: 'Marco Conversível' },
  { value: 'BBD', label: 'Dólar de Barbados' },
  { value: 'BDT', label: 'Taka de Bangladesh' },
  { value: 'BGN', label: 'Lev Búlgaro' },
  { value: 'BHD', label: 'Dinar do Bahrein' },
  { value: 'BIF', label: 'Franco Burundinense' },
  { value: 'BND', label: 'Dólar de Brunei' },
  { value: 'BOB', label: 'Boliviano' },
  { value: 'BSD', label: 'Dólar das Bahamas' },
  { value: 'BWP', label: 'Pula de Botswana' },
  { value: 'BYN', label: 'Rublo Bielorrusso' },
  { value: 'BZD', label: 'Dólar de Belize' },
  { value: 'CLP', label: 'Peso Chileno' },
  { value: 'CNH', label: 'Yuan chinês offshore' },
  { value: 'COP', label: 'Peso Colombiano' },
  { value: 'CRC', label: 'Colón Costarriquenho' },
  { value: 'CUP', label: 'Peso Cubano' },
  { value: 'CVE', label: 'Escudo cabo-verdiano' },
  { value: 'CZK', label: 'Coroa Checa' },
  { value: 'DJF', label: 'Franco do Djubouti' },
  { value: 'DKK', label: 'Coroa Dinamarquesa' },
  { value: 'DOG', label: 'Dogecoin' },
  { value: 'DOP', label: 'Peso Dominicano' },
  { value: 'DZD', label: 'Dinar Argelino' },
  { value: 'EGP', label: 'Libra Egípcia' },
  { value: 'ETB', label: 'Birr Etíope' },
  { value: 'FJD', label: 'Dólar de Fiji' },
  { value: 'GEL', label: 'Lari Georgiano' },
  { value: 'GHS', label: 'Cedi Ganês' },
  { value: 'GMD', label: 'Dalasi da Gâmbia' },
  { value: 'GNF', label: 'Franco de Guiné' },
  { value: 'GTQ', label: 'Quetzal Guatemalteco' },
  { value: 'HKD', label: 'Dólar de Hong Kong' },
  { value: 'HNL', label: 'Lempira Hondurenha' },
  { value: 'HRK', label: 'Kuna Croata' },
  { value: 'HTG', label: 'Gourde Haitiano' },
  { value: 'HUF', label: 'Florim Húngaro' },
  { value: 'IDR', label: 'Rupia Indonésia' },
  { value: 'ILS', label: 'Novo Shekel Israelense' },
  { value: 'INR', label: 'Rúpia Indiana' },
  { value: 'IQD', label: 'Dinar Iraquiano' },
  { value: 'IRR', label: 'Rial Iraniano' },
  { value: 'ISK', label: 'Coroa Islandesa' },
  { value: 'JMD', label: 'Dólar Jamaicano' },
  { value: 'JOD', label: 'Dinar Jordaniano' },
  { value: 'KES', label: 'Shilling Queniano' },
  { value: 'KGS', label: 'Som Quirguistanês' },
  { value: 'KHR', label: 'Riel Cambojano' },
  { value: 'KMF', label: 'Franco Comorense' },
  { value: 'KRW', label: 'Won Sul-Coreano' },
  { value: 'KWD', label: 'Dinar Kuwaitiano' },
  { value: 'KYD', label: 'Dólar das Ilhas Cayman' },
  { value: 'KZT', label: 'Tengue Cazaquistanês' },
  { value: 'MXN', label: 'Peso Mexicano' }
];